"use client";

import { useRouter } from "next/navigation";
import { ChatProvider } from "@/../context/ChatProvider";
import { useSessionExpiredModalStore } from "@/../lib/zustand/store";
import { SessionExpiredModal } from "../components/Modal/SessionExpiredModal";
import DesktopSidebar from "../components/SideBar";
import { signOut } from "next-auth/react";

const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

function MainLayout({ children }: { children: React.ReactNode }) {
  const { isOpen, close } = useSessionExpiredModalStore();
  const router = useRouter();

  return (
    <div className="flex min-h-screen w-full">
      <ChatProvider>
        <SessionExpiredModal
          isOpen={isOpen}
          handleClose={async () => {
            const signOutResponse = await signOut({
              redirect: false,
              callbackUrl: "/login",
            });

            router.push(signOutResponse?.url);
            close();
          }}
        />
        <DesktopSidebar />
        {children}
      </ChatProvider>
    </div>
  );
}

export default MainLayout;
