import DesktopSidebar from "../components/SideBar";

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen w-full">
      <DesktopSidebar />
      {children}
    </div>
  );
}

export default MainLayout;
