import { NextAuthProvider } from "../../context/NextAuthProvider";
import { ToastProvider } from "../../context/ToastProvider";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <NextAuthProvider>
          <ToastProvider>
            <main className={`${inter.variable} font-sans`}>{children}</main>
          </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}

export default RootLayout;
