"use client";

import { NextAuthProvider } from "@/../context/NextAuthProvider";
import { ToastProvider } from "@/../context/ToastProvider";
import { Inter, Montserrat, Roboto_Mono } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <NextUIProvider>
          <NextAuthProvider>
            <ToastProvider>
              <main>{children}</main>
            </ToastProvider>
          </NextAuthProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}

export default RootLayout;
